In [1]:
from games import TicTacToe

In [2]:
import torch

game = TicTacToe()
policy = torch.rand(9)  # Example policy
sym_pairs = game.symmetries(policy)

for i, (s, p) in enumerate(sym_pairs):
    print(f"Symmetry {i+1}:")
    print("State:\n", s)
    print("Policy:", p)
    print()

Symmetry 1:
State:
 tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
Policy: tensor([0.9295, 0.9486, 0.8727, 0.5686, 0.5670, 0.5375, 0.8573, 0.9761, 0.8592])

Symmetry 2:
State:
 tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
Policy: tensor([0.8727, 0.9486, 0.9295, 0.5375, 0.5670, 0.5686, 0.8592, 0.9761, 0.8573])

Symmetry 3:
State:
 tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
Policy: tensor([0.8727, 0.5375, 0.8592, 0.9486, 0.5670, 0.9761, 0.9295, 0.5686, 0.8573])

S

In [3]:
from self_play import SelfPlayManager
from games import TicTacToe
from net import TicTacToeNet

In [7]:
net = TicTacToeNet()

self_play_manager = SelfPlayManager(net, TicTacToe)
data = self_play_manager.generate_self_play(num_games=1000, num_workers=4)

[SelfPlayManager] Collecting 1000 games with 4 workers...


Self-play:  65%|██████████████████▉          | 653/1000 [00:17<00:09, 37.71it/s]
Traceback (most recent call last):
  File "/Users/vojtahavlicek/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/vojtahavlicek/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vojtahavlicek/Documents/GitHub/strategy-ai/alphazero/self_play.py", line 77, in _worker
    policy, action = mcts.run(game, temperature=temp)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vojtahavlicek/Documents/GitHub/strategy-ai/alphazero/mcts.py", line 75, in run
    key = self._game_to_key(node.game)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vojtahavlicek/Documents/GitHub/strategy-ai/alphazero/mcts.py", line 46, in _game_to_key
    return tuple(game.encode(device='cpu').squeeze(0).flatten().tolist())
                 ^^^^^^^^^^^^^

KeyboardInterrupt: 